### ISSUE TITLE
Typo in scripts/theme.js

### ISSUE THREAD

**Issue by Jackymancs4** [da2x/instapaper-webextension#4]
`document.body.styles.backgroundColor` is causing `TypeError: document.body.styles is undefined` when using themes other than the default.

I think what you meant was `document.body.style.backgroundColor`
You can replaced it here

https://github.com/da2x/instapaper-webextension/blob/93864495beb32689882fe5a3d5681fb66487edf5/scripts/theme.js#L31

and here:
https://github.com/da2x/instapaper-webextension/blob/93864495beb32689882fe5a3d5681fb66487edf5/scripts/theme.js#L36

**Comment by da2x** [comment]
Thank you for the report, @Jackymancs4. Fixed in f6db7f9.
