### ISSUE TITLE
Issue with styling

### ISSUE THREAD

**Issue by Jackymancs4** [da2x/instapaper-webextension#5]
Hello @da2x 
Sorry to bother you again.

Here https://github.com/da2x/instapaper-webextension/blob/10a1c823a07d2b5baad48493d60050546bd04218/scripts/theme.js#L36 in `theme.js` you use 
```js
document.body.style.backgroundColor = theme.colors.popout_text || theme.colors.textcolor;
```

but I think it should be 

```js
document.body.style.color = theme.colors.popout_text || theme.colors.textcolor;
```
to actually color the text.

Right now, every time a theme explicitly set text to black, the popup appears like this to me:
<img width="205" alt="Schermata 2019-03-19 alle 11 20 29" src="https://user-images.githubusercontent.com/6209647/54603505-ca133a00-4a44-11e9-928d-ecbe85362501.png">

**Comment by Jackymancs4** [comment]
Also, according to https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/theme#colors neither `popout` nor `popout_text` appears to be valid keys of a `theme` object.
I guess you meant `popup` and  `popup_text`.

Anyway, my suggestion is to completely remove the feature (deleting `themes.js`) as themes are rarely well formed objects and usually only the background image is used to 'set' the main color.

The addon's default white style is pretty nice.

**Comment by da2x** [comment]
Resolved by #6.

**Comment by da2x** [comment]
Partially resolved by #6. The remaining problem is that button elements don’t inherit the CSS color property. I’ll fix that and push out another update.

**Comment by da2x** [comment]
Version 1.2.3 submitted for review.

**Comment by Jackymancs4** [comment]
Thanks for the quick merge and push, but now with version 1.2.3 the problem just go "inverted".

<img width="213" alt="Schermata 2019-06-14 alle 15 18 24 2" src="https://user-images.githubusercontent.com/6209647/59512031-1fca7780-8eb8-11e9-9204-8c43c2771e51.png">

It works fine with a light theme, but since my default one is dark, right now it's even more of a problem than before.

**Comment by Jackymancs4** [comment]
@da2x Just a gentle ping to be sure you see this ;)

**Comment by da2x** [comment]
Hm. It works on Linux but not macOS.
I'll look at it again in a few hours.

**Comment by da2x** [comment]
Never mind. It works just fine with any properly designed theme. I installed 43 popular themes from AMO and all but one set a proper background to text contrast ratio. I thought there were an issue on macOS but that was something custom to my system. Also tested on Windows and it works just fine.

The one broken theme had specified the popup background color `theme.colors.popup` (default light) but not `theme.colors.popup_text` (default dark). When you set the former to a dark color and leave the dark default for the latter you end up with this problem.

Please contact the theme author and ask them to fix their theme, or consider using another theme. Most themes seems to work just fine; based on my random sample of popular themes. You can link them to the [MDN reference for themes](https://developer.mozilla.org/en/docs/Mozilla/Add-ons/WebExtensions/manifest.json/theme#Syntax).

**Comment by Jackymancs4** [comment]
My specific problem arise from the theme object being:
```json
{
    "colors": {
      "accentcolor": "rgb(30,35,39)",
      "bookmark_text": null,
      "button_background_active": null,
      "button_background_hover": null,
      "frame": null,
      "frame_inactive": null,
      "icons": null,
      "icons_attention": null,
      "ntp_background": null,
      "ntp_text": null,
      "popup": null,
      "popup_border": null,
      "popup_highlight": null,
      "popup_highlight_text": null,
      "popup_text": null,
      "sidebar": null,
      "sidebar_border": null,
      "sidebar_highlight": null,
      "sidebar_highlight_text": null,
      "sidebar_text": null,
      "tab_background_separator": null,
      "tab_background_text": null,
      "tab_line": "rgb(255,255,255)",
      "tab_loading": null,
      "tab_selected": null,
      "tab_text": null,
      "textcolor": "rgb(255,255,255)",
      "toolbar": "rgb(30,35,39)",
      "toolbar_bottom_separator": "rgb(30,35,39)",
      "toolbar_field": null,
      "toolbar_field_border": null,
      "toolbar_field_border_focus": null,
      "toolbar_field_focus": null,
      "toolbar_field_highlight": null,
      "toolbar_field_highlight_text": null,
      "toolbar_field_separator": null,
      "toolbar_field_text": null,
      "toolbar_field_text_focus": null,
      "toolbar_text": null,
      "toolbar_top_separator": null,
      "toolbar_vertical_separator": null
    },
    "icons": null,
    "images": null,
    "properties": null
  }
```

As you can see, it uses the deprecated and soon to be removed `accentcolor` key instead of `frame` or `popup`.

> It works just fine with any properly designed theme.

Yes, as I tried to express in

> Anyway, my suggestion is to completely remove the feature (deleting themes.js) as themes are rarely well formed objects and usually only the background image is used to 'set' the main color.

this is a generally known issue.

While I agree with you on a technical level, I find the 'ask other to adapt their code to mine' kind of mindset very detrimental to the final user, and I think this is an easy road to a very bad experience, if it'll ever happen to escape a relatively simple Instapaper related addon.

> or consider using another theme.

As an example, the take or leave situation some user might end up with.

As a final request, consider the possibility to add an option to disable automatic styling, since you cannot (or at least shouldn't) assume/hope that your users use a well formed theme.
